### ISSUE TITLE
Deprecated Code to Remove

### ISSUE THREAD

**Issue by connorshea** [SuiteCRM/SuiteCRM#7744]
This is a list of deprecated code/functionality that needs to be removed in the next major version (7.12 or 8.0) of SuiteCRM.

- [x] Remove PHP 4-style constructors (Issue #4754, PR #6750) - this one can probably be removed in a minor release, honestly.
- [ ] Remove Zend files (Related PRs: #7672, #7719) Full removal: #8094
   - We should also remove Zend Gdata entirely, since it's not used for anything in the core codebase as far as I can tell.
- [ ] Remove Zend Lucene files (Related PR: #7690)
- [x] Remove Smarty files (Related PRs: #7591, #7729) Full removal: #8093
- [x] Remove HTMLPurifier files (related PRs: #5959) - This is already done in develop, I guess that's sufficient?
- [ ] Whatever `include/clean.php` is for: https://github.com/salesagility/SuiteCRM/blob/df18433e4bd429ecd754953a6354e38f37893efd/include/clean.php
- [ ] Remove the functions deprecated in these PRs:
  - [ ] #8441
  - [ ] #8297
  - [ ] #8379
  - [ ] #8252
  - [ ] #8258

You can also see some of the files that need to be removed in [`deprecated.php`](https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/deprecated.php).

If I'm missing any, please speak up in the comments.

**Comment by connorshea** [comment]
Putting this here since I don't really have a better place to keep it, Dillon's script for replacing vendored files with a deprecation warning:

```shell
#!/usr/bin/env bash

for i in `cat file_list.txt | sed '/^$/d;s/^ *//;s/ *$//'`; 
  do mkdir -p `dirname $i`; 
     touch `echo $(dirname $i)$(echo "/")$(basename $i)`;
     cat content.txt >> `echo $(dirname $i)$(echo "/")$(basename $i)`;
  done
```

**Comment by connorshea** [comment]
We should probably remove this deprecated function, it's only used in a single test file as far s I can tell:
https://github.com/salesagility/SuiteCRM/blob/046949fbb7ed19794f14cbfdd7c7f83c09789e3a/modules/Users/User.php#L1042-L1056

**Comment by connorshea** [comment]
This should be deprecated with a `@deprecated` tag: https://github.com/salesagility/SuiteCRM/blob/df18433e4bd429ecd754953a6354e38f37893efd/include/utils.php#L1640-L1653

**Comment by connorshea** [comment]
ListView has some functions named `getArrowStart`, `getArrowEnd`, and `getArrowUpDownEnd` that have been deprecated for >2 years now (there's also `getArrowUpDownStart` but that's not deprecated for whatever reason).

`getArrowUpDownStart` and `getArrowUpDownEnd` are both used in two places right now, the other two are unused. We should probably remove/replace their usage, especially since `getArrowUpDownEnd` just returns a blank string right now lol

https://github.com/salesagility/SuiteCRM/blob/df18433e4bd429ecd754953a6354e38f37893efd/include/ListView/ListView.php#L1940-L1987

**Comment by connorshea** [comment]
Does anyone know of a tool for finding functions that are unused?

I've found a few bits of code that are unused and could be deprecated without any problem, e.g. [`add_http` in `utils.php`](https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/include/utils.php#L2004).

**Comment by connorshea** [comment]
It seems like this code should be updated since PHP 5.2 has long been dead.

https://github.com/salesagility/SuiteCRM/blob/c3cd37ab16fd9c9c472eee8c36210400a16a69f9/include/SugarDateTime.php#L111-L133

**Comment by holdusback** [comment]
Thanks a lot for this ! 

While debugging I saw this error (PHP4 Style Constructors are deprecated and will be remove in 7.8, please update your code) everywhere !

**Comment by connorshea** [comment]
We can deprecate [`generate_search_where`](https://github.com/salesagility/SuiteCRM/blob/899690fe30f73aeccfe9d31bcba0a50d2dc5e7f0/include/utils.php#L4352) as well, it's unused.
